---
organizationLogo: "$ref:/systemFiles/lora-logo.png"
documentTitle: "LoRaWAN Remote Multicast Setup Specification"
documentVersion: "v1.0.0"
documentDate: "September 10, 2018"
documentStatus: "Final relase"
copyrightYear: "2018"
workingGroup: "FUOTA"
organizationName: "LoRA Alliance"
committeeChairName-1: "N.SORNIN"
committeeChairCompany-1: "(Semtech)"
committeeChairName-2: "A.YEGIN"
committeeChairCompany-2: "(Actility)"
groupChairName-1: "J.CATALANO"
groupChairCompany-1: "(Kerlink)"
groupChairName-2: "N.SORNIN"
groupChairCompany-2: "(Semtech)"
editorName-1: "J.CATALANO"
editorCompany-1: "(Kerlink)"
contributorName-1: "J.CATALANO"
contributorCompany-1: "(Kerlink)"
contributorName-2: "J-P.COUPIGNY"
contributorCompany-2: "(STMicroelectronics)"
contributorName-3: "J.DELCLEF"
contributorCompany-3: "(STMicroelectronics)"
contributorName-4: "A.GRIGORE"
contributorCompany-4: "(Flashnet)"
contributorName-5: "J.SCHLARB"
contributorCompany-5: "(Comcast)"
contributorName-6: "N.SORNIN"
contributorCompany-6: "(Semtech)"
contributorName-7: "J.STOKKING"
contributorCompany-7: "(The Things Network Foundation)"
contributorName-8: "A.YEGIN"
contributorCompany-8: "(Actility)"
systemFiles:
  - page-1: $ref:/systemFiles/page-1.html
  - page-2: $ref:/systemFiles/page-2.html
  - document: $ref:/systemFiles/document.html
  - license: $ref:/license.txt
userFiles:
  - RMSS.md
---