---
documentTitle: "AV1 Codec ISO Media File Format Binding"
documentVersion: "1.0.0"
documentDate: "DD/MM/YYYY"
documentName: "AV1 Codec ISO Media File Format Binding V1.0.0 "
thisVersion: "https://aomediacodec.github.io/av1-isobmff//"
issueTrackingName: "GitHub"
issueTrackingURL: "https://github.com/AOMediaCodec/av1-isobmff/issues/"
editorName-1: "Cyril Concolato"
editorEmail-1: "cconcolato@netflix.com"
editorCompany-1: "(Netflix)"
editorName-2: "Tom Finegan"
editorEmail-2: "tom.finegan@google.com"
editorCompany-2: "(Google)"
copyrightYear: "2018"
organizationName: "The Alliance for Open Media"
toc: "True"
tot: "True"
tof: "True"
frontcoverHeader-1-1: {documentDate}
frontcoverHeader-1-2: {documentName}
frontcoverFooter-1-1: {thisVersion}
frontcoverFooter-1-2: {Page}
documentHeader-1-1: {documentDate}
documentHeader-1-2: {documentName}
documentFooter-1-1: {thisVersion}
documentFooter-1-3: {Page}


files:
 - Abstract.html
 - AOM.md
---
