---
documentTitle: "AV1 Codec ISO Media File Format Binding"
documentVersion: "1.0.0"
documentDate: "DD/MM/YYYY"
documentName: "AV1 Codec ISO Media File Format Binding V1.0.0 "
thisVersion: "https://aomediacodec.github.io/av1-isobmff//"
issueTrackingName: "GitHub"
issueTrackingURL: "https://github.com/AOMediaCodec/av1-isobmff/issues/"
editorName-1: "Cyril Concolato"
editorEmail-1: "cconcolato@netflix.com"
editorCompany-1: "(Netflix)"
editorName-2: "Tom Finegan"
editorEmail-2: "tom.finegan@google.com"
editorCompany-2: "(Google)"
copyrightYear: "2018"
organizationName: "The Alliance for Open Media"
systemFiles:
 - page-1: "$ref:#/systemFiles/page-1.html"
 - Abstract: "$ref:#/systemFiles/Abstract.html"
 - document: "$ref:#/systemFiles/document.html"
 - license: "$ref:#/license.txt"

userFiles:
 - Abstract.md
 - AOM.md
---
