---
layout: "default"
frontCoverLogo: "oma-logo.png"
title: "[Name of Specification]"
status: "Draft"
version: "x.y.z"
date: "yyyy-mm-dd"
documentName: "OMA-TS-[FunctionalName]-Vx_y_z-yyyymmdd-D"
copyrightYear: "2020"
organizationName: "Open Mobile Alliance"
frontCoverHeader-1-1: "oma-logo.png"
frontCoverFooter-1-1: "(C) 2020 Open Mobile Alliance"
frontCoverFooter-2-1: "Used with the permission of the Open Mobile Alliance under the terms as stated in this document."
documentHeader-1-1: {documentName}
documentHeader-1-3: {page}
documentHeaderLine: "True"
documentFooter-1-1: "C" {copyrightYear} {organizationName}
documentFooter-2-1: {frontCoverFooter-2-1}
documentFooterLine: "True"

files:
 - License.txt
 - OMA_template_spec.md
 - Appendix_A.md
 - Appendix_B.md
---

```
title: 
Add title of the Specification. Example title: Lightweight Machine to Machine Technical Specification: Core
DELETE THIS COMMENT
```
```
Stutus:
Select the appropriate status of the document. Example status: Draft or Candiate or Approved
DELETE THIS COMMENT
```
```
Version:
Specify the version of the document x.y.z - Example version: 1.1.1
DELETE THIS COMMENT
```
```
Date:
Date only to be added for Candidate or Approved documents with a yyyy-mm-dd format. Example date: 2018-01-23
For Draft documents leave the date empty. Example date:
DELETE THIS COMMENT
```
```
documentName:
Enter document name OMA-doc_type-enabler_type-Vx_y. Example documentName: OMA-TS-LightweightM2M_Core-V1_1
DELETE THIS COMMENT
```
```
files:
List all the md files that are contained within the document specification
Example
  - License.txt
  - OMA-TS-LightweightM2M_Core-V1_1.md
  - Appendix_A.md
  - Appendix_B.md
  
DELETE THIS COMMENT
```

